[project]
name = "NF1_organoid_profile_analysis"
r_version = ">=4.3.0"

[dependencies]
IRkernel = "*"
VennDiagram = "*"
arrow = "*"
circlize = "*"
cowplot = "*"
devtools = "*"
dplyr = "*"
ggVennDiagram = "*"
ggplot2 = "*"
ggrastr = "*"
ggrepel = "*"
ggupset = "*"
ggvenn = "*"
hrbrthemes = "*"
magick = "*"
patchwork = "*"
pheatmap = "*"
tidyr = "*"
tm = "*"

[dependencies.ComplexHeatmap]
bioc = true
