upload_data_to_hf_bucket:
	uv run python3 sync_data.py upload

download_data_from_hf_bucket:
	uv run python3 sync_data.py download

run_app_locally:
	bash ./run_app.sh

all_data: upload_data_to_hf_bucket download_data_from_hf_bucket

all: all_data run_app_locally
